// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdowns': string;
  'navbar': string;
}
export const cssExports: CssExports;
export default cssExports;
